# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0004_auto_20171017_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/uploads/2017/10/16/dell1.jpg', max_length=200, upload_to='product/uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
