# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0006_auto_20171018_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
