# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0007_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
