# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0009_auto_20171025_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
