# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0013_auto_20171105_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_delivery_address', to='computerapp.DeliveryAddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='computerapp.DeliveryAddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='computerapp.Product'),
        ),
    ]
