# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0014_auto_20171105_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delivery_address', to='computerapp.DeliveryAddress'),
        ),
    ]
