# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0015_auto_20171105_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'new'), ('1', 'not paid'), ('2', 'paid'), ('3', 'transport'), ('4', 'closed')], default='0', max_length=2),
        ),
    ]
